# Generated by Django 4.2.2 on 2023-06-25 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['-id'], 'verbose_name': 'Custom User', 'verbose_name_plural': 'Custom Users'},
        ),
    ]
