# Generated by Django 4.2.2 on 2023-07-01 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TourLocationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=225, null=True)),
                ('code', models.CharField(max_length=3, null=True)),
            ],
            options={
                'verbose_name': 'Tour Location',
                'verbose_name_plural': 'Tour Locations',
                'ordering': ['-id'],
            },
        ),
    ]
