# Generated by Django 4.2.2 on 2023-08-15 06:01

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("app_flight", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TourLocationModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("country", django_countries.fields.CountryField(max_length=2)),
                ("district", models.CharField(max_length=122, null=True)),
                (
                    "location_name",
                    models.CharField(
                        max_length=225, null=True, verbose_name="location name"
                    ),
                ),
                ("code", models.CharField(max_length=3, null=True)),
            ],
            options={
                "verbose_name": "Tour Location",
                "verbose_name_plural": "Tour Locations",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="TourPackageModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("package_title", models.CharField(max_length=525, null=True)),
                ("tour_duration", models.IntegerField(blank=True, null=True)),
                (
                    "peoples_limit",
                    models.PositiveIntegerField(blank=True, default=1, null=True),
                ),
                ("details", ckeditor_uploader.fields.RichTextUploadingField(null=True)),
                ("options", ckeditor_uploader.fields.RichTextUploadingField(null=True)),
                ("policy", ckeditor_uploader.fields.RichTextUploadingField(null=True)),
                ("adult_traveler", models.PositiveIntegerField(default=1, null=True)),
                ("child_traveler", models.PositiveIntegerField(blank=True, null=True)),
                ("infant_traveler", models.PositiveIntegerField(blank=True, null=True)),
                ("journey_date", models.DateTimeField()),
                ("package_price", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "discount",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app_flight.discount",
                    ),
                ),
                (
                    "tour_location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app_tour.tourlocationmodel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tour Package",
                "verbose_name_plural": "Tour Packages",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="TourPackageImages",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image_title", models.CharField(max_length=122, null=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="tour_package_images"
                    ),
                ),
                (
                    "package",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app_tour.tourpackagemodel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tour Package Image",
                "verbose_name_plural": "Tour Packages Images",
                "ordering": ["-id"],
            },
        ),
    ]
