# Generated by Django 4.2.2 on 2023-08-17 17:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tour', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourpackagemodel',
            name='journey_date',
            field=models.DateField(default=datetime.datetime(2023, 8, 17, 17, 40, 30, 821098, tzinfo=datetime.timezone.utc)),
        ),
    ]
