# Generated by Django 4.2.2 on 2023-07-01 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_flight', '0003_alter_airplaneticketmodel_adult_tax_and_more'),
        ('app_tour', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourlocationmodel',
            name='location_name',
            field=models.CharField(max_length=225, null=True, verbose_name='location name'),
        ),
        migrations.CreateModel(
            name='TourPackageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_title', models.CharField(max_length=225, null=True)),
                ('overview', models.TextField(max_length=755, null=True)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('requirements', models.TextField(max_length=755, null=True)),
                ('location', models.CharField(max_length=122, null=True)),
                ('timing', models.CharField(max_length=122, null=True)),
                ('description', models.TextField(max_length=755, null=True)),
                ('additional_information', models.TextField(max_length=755, null=True)),
                ('travel_tips', models.TextField(max_length=755, null=True)),
                ('policy', models.TextField(max_length=755, null=True)),
                ('adult_traveler', models.IntegerField(default=1, null=True)),
                ('child_traveler', models.IntegerField(blank=True, null=True)),
                ('infant_traveler', models.IntegerField(blank=True, null=True)),
                ('journey_date', models.DateTimeField()),
                ('package_price', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('discount', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_flight.discountmodel')),
            ],
            options={
                'verbose_name': 'Tour Package',
                'verbose_name_plural': 'Tour Packages',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='TourPackageImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_title', models.CharField(max_length=122, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='tour_package_images')),
                ('package', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_tour.tourpackagemodel')),
            ],
            options={
                'verbose_name': 'Tour Package Image',
                'verbose_name_plural': 'Tour Packages Images',
                'ordering': ['-id'],
            },
        ),
    ]
