# Generated by Django 4.2.2 on 2023-07-04 11:55

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app_tour', '0002_alter_tourlocationmodel_location_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tourpackagemodel',
            old_name='location',
            new_name='district',
        ),
        migrations.RenameField(
            model_name='tourpackagemodel',
            old_name='duration',
            new_name='tour_duration',
        ),
        migrations.RemoveField(
            model_name='tourpackagemodel',
            name='additional_information',
        ),
        migrations.RemoveField(
            model_name='tourpackagemodel',
            name='description',
        ),
        migrations.RemoveField(
            model_name='tourpackagemodel',
            name='overview',
        ),
        migrations.RemoveField(
            model_name='tourpackagemodel',
            name='requirements',
        ),
        migrations.RemoveField(
            model_name='tourpackagemodel',
            name='timing',
        ),
        migrations.RemoveField(
            model_name='tourpackagemodel',
            name='travel_tips',
        ),
        migrations.AddField(
            model_name='tourpackagemodel',
            name='country',
            field=django_countries.fields.CountryField(default='', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tourpackagemodel',
            name='details',
            field=models.TextField(max_length=2055, null=True),
        ),
        migrations.AddField(
            model_name='tourpackagemodel',
            name='options',
            field=models.TextField(max_length=2055, null=True),
        ),
        migrations.AddField(
            model_name='tourpackagemodel',
            name='peoples_limit',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='tourpackagemodel',
            name='tour_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_tour.tourlocationmodel'),
        ),
        migrations.AlterField(
            model_name='tourpackagemodel',
            name='adult_traveler',
            field=models.PositiveIntegerField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name='tourpackagemodel',
            name='child_traveler',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tourpackagemodel',
            name='infant_traveler',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tourpackagemodel',
            name='package_title',
            field=models.CharField(max_length=525, null=True),
        ),
        migrations.AlterField(
            model_name='tourpackagemodel',
            name='policy',
            field=models.TextField(max_length=2055, null=True),
        ),
    ]
