# Generated by Django 4.2.2 on 2023-07-06 15:58

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_tour", "0003_rename_location_tourpackagemodel_district_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tourpackagemodel",
            name="details",
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AlterField(
            model_name="tourpackagemodel",
            name="options",
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AlterField(
            model_name="tourpackagemodel",
            name="policy",
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
    ]
