# Generated by Django 4.2.2 on 2023-07-19 13:58

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):
    dependencies = [
        ("app_tour", "0004_alter_tourpackagemodel_details_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tourpackagemodel",
            name="country",
        ),
        migrations.RemoveField(
            model_name="tourpackagemodel",
            name="district",
        ),
        migrations.AddField(
            model_name="tourlocationmodel",
            name="country",
            field=django_countries.fields.CountryField(default="", max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tourlocationmodel",
            name="district",
            field=models.CharField(max_length=122, null=True),
        ),
    ]
