# Generated by Django 4.2.2 on 2023-08-07 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tour', '0005_remove_tourpackagemodel_country_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_name', models.CharField(max_length=122, null=True, verbose_name='Name')),
                ('cover_image', models.ImageField(null=True, upload_to='tour_package_images', verbose_name='Cover Image')),
                ('link', models.URLField(blank=True, default='#', null=True, verbose_name='Hotel Link')),
            ],
            options={
                'verbose_name': 'Hotel',
                'verbose_name_plural': 'Hotels',
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='tourpackagemodel',
            name='hotel',
            field=models.ManyToManyField(null=True, to='app_tour.hotelmodel'),
        ),
    ]
