# Generated by Django 4.2.2 on 2023-08-14 16:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_tour', '0006_hotelmodel_tourpackagemodel_hotel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tourpackagemodel',
            name='adult_traveler',
        ),
        migrations.RemoveField(
            model_name='tourpackagemodel',
            name='child_traveler',
        ),
        migrations.RemoveField(
            model_name='tourpackagemodel',
            name='infant_traveler',
        ),
        migrations.AlterField(
            model_name='tourpackagemodel',
            name='hotel',
            field=models.ManyToManyField(to='app_tour.hotelmodel'),
        ),
        migrations.CreateModel(
            name='TourOrderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adult_traveler', models.PositiveIntegerField(default=1, null=True)),
                ('child_traveler', models.PositiveIntegerField(blank=True, null=True)),
                ('infant_traveler', models.PositiveIntegerField(blank=True, null=True)),
                ('journey_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('package', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_tour.tourpackagemodel')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tour Package Order',
                'verbose_name_plural': 'Tour Package Orders',
                'ordering': ['-id'],
            },
        ),
    ]
