# Generated by Django 4.2.2 on 2023-08-14 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tour', '0007_remove_tourpackagemodel_adult_traveler_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourordermodel',
            name='hotel_name',
            field=models.CharField(max_length=525, null=True),
        ),
    ]
