# Generated by Django 4.2.2 on 2023-08-15 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tour', '0008_tourordermodel_hotel_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourpackagemodel',
            name='Children_package_price',
            field=models.FloatField(default=50, help_text='enter 50 percent children traveler', null=True),
        ),
        migrations.AddField(
            model_name='tourpackagemodel',
            name='Infant_package_price',
            field=models.FloatField(default=90, help_text='enter 90 percent infant traveler', null=True),
        ),
    ]
