# Generated by Django 4.2.2 on 2023-06-25 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AirportModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=122, null=True)),
                ('country', models.CharField(max_length=122, null=True)),
                ('airport', models.CharField(max_length=122, null=True)),
                ('code', models.CharField(max_length=3, null=True)),
            ],
            options={
                'verbose_name': 'Airport',
                'verbose_name_plural': 'Airports',
                'ordering': ['-id'],
            },
        ),
    ]
