# Generated by Django 4.2.2 on 2023-08-17 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_flight', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airplaneticket',
            name='child_discount',
            field=models.FloatField(blank=True, default=50, help_text='Enter 50 percent children traveler', null=True),
        ),
        migrations.AlterField(
            model_name='airplaneticket',
            name='infant_discount',
            field=models.FloatField(blank=True, default=90, help_text='Enter 90 percent infant traveler', null=True),
        ),
    ]
