# Generated by Django 4.2.2 on 2023-06-27 16:34

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app_flight', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AirplaneModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airplane_name', models.CharField(max_length=122, null=True)),
                ('airplane_model', models.CharField(max_length=122, null=True)),
                ('airplane_logo', models.ImageField(blank=True, null=True, upload_to='airplane_logo')),
            ],
            options={
                'verbose_name': 'Airplane',
                'verbose_name_plural': 'Airplanes',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='AirPlaneTicketModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_type', models.CharField(choices=[('Economy', 'Economy'), ('Business', 'Business')], default='Economy', max_length=122, null=True)),
                ('base_adult_fare', models.FloatField(null=True)),
                ('base_child_fare', models.FloatField(null=True)),
                ('base_infant_fare', models.FloatField(null=True)),
                ('adult_tax', models.FloatField(null=True)),
                ('child_tax', models.FloatField(null=True)),
                ('infant_tax', models.FloatField(null=True)),
                ('baggage_cabin', models.FloatField(null=True)),
                ('baggage_checkin', models.FloatField(null=True)),
                ('start_date', models.DateTimeField(auto_now=True)),
                ('end_date', models.DateTimeField(auto_now=True)),
                ('airplane', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_flight.airplanemodel')),
            ],
            options={
                'verbose_name': 'AirPlane Ticket',
                'verbose_name_plural': 'AirPlane Tickets',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='DiscountModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_name', models.CharField(max_length=122, null=True)),
                ('discount_code', models.CharField(max_length=122, null=True)),
                ('amount', models.FloatField(null=True)),
                ('start_date', models.DateTimeField(auto_now=True)),
                ('end_date', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Discount',
                'verbose_name_plural': 'Discounts',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='OrderFlightModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('select_title', models.CharField(choices=[('MR.', 'MR.'), ('MS.', 'MS.'), ('MRS.', 'MRS.'), ('MASTER..', 'MASTER.'), ('MISS.', 'MISS.')], default='MR.', max_length=122, null=True)),
                ('first_name', models.CharField(max_length=122, null=True)),
                ('last_name', models.CharField(max_length=122, null=True)),
                ('email', models.CharField(max_length=122, null=True)),
                ('phone', models.CharField(max_length=122, null=True)),
                ('date_of_birth', models.DateField(auto_now=True, null=True)),
                ('nationality', django_countries.fields.CountryField(max_length=2)),
                ('ticket', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_flight.airplaneticketmodel')),
            ],
            options={
                'verbose_name': 'Order Flight',
                'verbose_name_plural': 'Order Flights',
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='airplaneticketmodel',
            name='discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_flight.discountmodel'),
        ),
        migrations.AddField(
            model_name='airplaneticketmodel',
            name='location_from',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='location_from', to='app_flight.airportmodel'),
        ),
        migrations.AddField(
            model_name='airplaneticketmodel',
            name='location_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='location_to', to='app_flight.airportmodel'),
        ),
    ]
