# Generated by Django 4.2.2 on 2023-08-17 18:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_flight', '0002_alter_airplaneticket_child_discount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='payment_amount',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='payment_date',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='payment_status',
        ),
        migrations.AddField(
            model_name='payment',
            name='adults_fare',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='childrens_fare',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='infants_fare',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='is_paid',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='sub_total_fare',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='total_fare',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='total_traveler',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='user_card_name',
            field=models.CharField(max_length=125, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='user_card_number',
            field=models.CharField(max_length=125, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='user_cvc_number',
            field=models.CharField(max_length=125, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='user_postal_code',
            field=models.CharField(max_length=125, null=True),
        ),
    ]
