# Generated by Django 4.2.2 on 2023-07-01 16:52

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app_flight', '0002_airplanemodel_airplaneticketmodel_discountmodel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airplaneticketmodel',
            name='adult_tax',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='airplaneticketmodel',
            name='baggage_cabin',
            field=models.FloatField(blank=True, null=True, verbose_name='Baggage KG (cabin)'),
        ),
        migrations.AlterField(
            model_name='airplaneticketmodel',
            name='baggage_checkin',
            field=models.FloatField(blank=True, null=True, verbose_name='Baggage KG (check-in)'),
        ),
        migrations.AlterField(
            model_name='airplaneticketmodel',
            name='base_adult_fare',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='airplaneticketmodel',
            name='base_child_fare',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='airplaneticketmodel',
            name='base_infant_fare',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='airplaneticketmodel',
            name='child_tax',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='airplaneticketmodel',
            name='infant_tax',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='airportmodel',
            name='country',
            field=django_countries.fields.CountryField(default='', max_length=2),
            preserve_default=False,
        ),
    ]
