# Generated by Django 4.2.2 on 2023-08-17 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_flight', '0003_remove_payment_payment_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ticket',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_flight.airplaneticket'),
        ),
    ]
