# Generated by Django 4.2.2 on 2023-08-17 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_flight', '0004_order_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='details',
            field=models.CharField(blank=True, max_length=999, null=True),
        ),
    ]
