# Generated by Django 4.2.2 on 2023-07-06 15:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("app_flight", "0004_airplaneticketmodel_duration"),
    ]

    operations = [
        migrations.RenameField(
            model_name="airplaneticketmodel",
            old_name="base_adult_fare",
            new_name="base_price",
        ),
        migrations.RemoveField(
            model_name="airplaneticketmodel",
            name="adult_tax",
        ),
        migrations.RemoveField(
            model_name="airplaneticketmodel",
            name="base_child_fare",
        ),
        migrations.RemoveField(
            model_name="airplaneticketmodel",
            name="base_infant_fare",
        ),
        migrations.RemoveField(
            model_name="airplaneticketmodel",
            name="child_tax",
        ),
        migrations.RemoveField(
            model_name="airplaneticketmodel",
            name="infant_tax",
        ),
        migrations.AddField(
            model_name="airplaneticketmodel",
            name="child_discount",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="airplaneticketmodel",
            name="infant_discount",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="airplaneticketmodel",
            name="tax",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="airplaneticketmodel",
            name="duration",
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name="airplaneticketmodel",
            name="end_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="airplaneticketmodel",
            name="start_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
