# Generated by Django 4.2.2 on 2023-07-24 04:59

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_flight', '0006_remove_airplaneticketmodel_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='airplaneticketmodel',
            name='policy',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
